[package]
name = "gamingguy84/reactivestate"
version = "0.1.6"
description = "A idiomatic state replication package."
license = "MIT"
authors = ["GamingGuy84"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["src", "src/*", "default.project.json", "LICENSE", "wally.toml", "README.md"]

[dependencies]
replica = "ivasmigins/replica@0.1.0"
lemonsignal = "data-oriented-house/lemonsignal@1.11.0"